using System.Globalization;
using System.Text.Json;

namespace Gridly.Localization;

public static class GridlyText
{
    private static readonly Dictionary<string, Dictionary<GridlyLanguage, string>> Texts = new(StringComparer.OrdinalIgnoreCase)
    {
        ["Filtering"] = new() { [GridlyLanguage.Turkish]="Filtreleme", [GridlyLanguage.English]="Filtering", [GridlyLanguage.German]="Filtern", [GridlyLanguage.French]="Filtrage", [GridlyLanguage.Spanish]="Filtrado", [GridlyLanguage.Italian]="Filtro", [GridlyLanguage.Russian]="Фильтр", [GridlyLanguage.Arabic]="تصفية", [GridlyLanguage.Chinese]="筛选", [GridlyLanguage.Japanese]="フィルター" },
        ["FilterStyle"] = new() { [GridlyLanguage.Turkish]="Filtre stili", [GridlyLanguage.English]="Filter style", [GridlyLanguage.German]="Filterstil", [GridlyLanguage.French]="Style de filtre", [GridlyLanguage.Spanish]="Estilo de filtro", [GridlyLanguage.Italian]="Stile filtro", [GridlyLanguage.Russian]="Стиль фильтра", [GridlyLanguage.Arabic]="نمط التصفية", [GridlyLanguage.Chinese]="筛选样式", [GridlyLanguage.Japanese]="フィルター形式" },
        ["SortAscending"] = new() { [GridlyLanguage.Turkish]="Artan sırala", [GridlyLanguage.English]="Sort ascending", [GridlyLanguage.German]="Aufsteigend sortieren", [GridlyLanguage.French]="Tri croissant", [GridlyLanguage.Spanish]="Orden ascendente", [GridlyLanguage.Italian]="Ordina crescente", [GridlyLanguage.Russian]="По возрастанию", [GridlyLanguage.Arabic]="ترتيب تصاعدي", [GridlyLanguage.Chinese]="升序排序", [GridlyLanguage.Japanese]="昇順で並べ替え" },
        ["SortDescending"] = new() { [GridlyLanguage.Turkish]="Azalan sırala", [GridlyLanguage.English]="Sort descending", [GridlyLanguage.German]="Absteigend sortieren", [GridlyLanguage.French]="Tri décroissant", [GridlyLanguage.Spanish]="Orden descendente", [GridlyLanguage.Italian]="Ordina decrescente", [GridlyLanguage.Russian]="По убыванию", [GridlyLanguage.Arabic]="ترتيب تنازلي", [GridlyLanguage.Chinese]="降序排序", [GridlyLanguage.Japanese]="降順で並べ替え" },
        ["Unsort"] = new() { [GridlyLanguage.Turkish]="Sıralamayı kaldır", [GridlyLanguage.English]="Unsort", [GridlyLanguage.German]="Sortierung entfernen", [GridlyLanguage.French]="Annuler le tri", [GridlyLanguage.Spanish]="Quitar orden", [GridlyLanguage.Italian]="Rimuovi ordinamento", [GridlyLanguage.Russian]="Без сортировки", [GridlyLanguage.Arabic]="إزالة الترتيب", [GridlyLanguage.Chinese]="取消排序", [GridlyLanguage.Japanese]="並べ替え解除" },
        ["ClearSort"] = new() { [GridlyLanguage.Turkish]="Tüm sıralamayı temizle / default sıraya dön", [GridlyLanguage.English]="Clear all sorting / return to default order", [GridlyLanguage.German]="Alle Sortierungen löschen / Standardreihenfolge", [GridlyLanguage.French]="Effacer tous les tris / ordre par défaut", [GridlyLanguage.Spanish]="Borrar orden / volver al orden inicial", [GridlyLanguage.Italian]="Cancella ordinamento / ordine predefinito", [GridlyLanguage.Russian]="Очистить сортировку / порядок по умолчанию", [GridlyLanguage.Arabic]="مسح الترتيب / العودة للوضع الافتراضي", [GridlyLanguage.Chinese]="清除排序 / 恢复默认顺序", [GridlyLanguage.Japanese]="すべての並べ替えを解除 / 既定順へ" },
        ["UnsortColumn"] = new() { [GridlyLanguage.Turkish]="Bu kolonu unsort yap", [GridlyLanguage.English]="Unsort this column", [GridlyLanguage.German]="Diese Spalte unsortieren", [GridlyLanguage.French]="Annuler le tri de cette colonne", [GridlyLanguage.Spanish]="Quitar orden de esta columna", [GridlyLanguage.Italian]="Rimuovi ordinamento colonna", [GridlyLanguage.Russian]="Убрать сортировку столбца", [GridlyLanguage.Arabic]="إزالة ترتيب هذا العمود", [GridlyLanguage.Chinese]="取消此列排序", [GridlyLanguage.Japanese]="この列の並べ替えを解除" },
        ["FreezeColumn"] = new() { [GridlyLanguage.Turkish]="Bu kolonu sabitle", [GridlyLanguage.English]="Freeze this column", [GridlyLanguage.German]="Diese Spalte fixieren", [GridlyLanguage.French]="Figer cette colonne", [GridlyLanguage.Spanish]="Fijar esta columna", [GridlyLanguage.Italian]="Blocca questa colonna", [GridlyLanguage.Russian]="Закрепить столбец", [GridlyLanguage.Arabic]="تثبيت هذا العمود", [GridlyLanguage.Chinese]="冻结此列", [GridlyLanguage.Japanese]="この列を固定" },
        ["ClearFrozenColumns"] = new() { [GridlyLanguage.Turkish]="Sabit kolonları kaldır", [GridlyLanguage.English]="Clear frozen columns", [GridlyLanguage.German]="Fixierte Spalten lösen", [GridlyLanguage.French]="Libérer les colonnes figées", [GridlyLanguage.Spanish]="Quitar columnas fijadas", [GridlyLanguage.Italian]="Sblocca colonne", [GridlyLanguage.Russian]="Снять закрепление", [GridlyLanguage.Arabic]="إلغاء تثبيت الأعمدة", [GridlyLanguage.Chinese]="取消冻结列", [GridlyLanguage.Japanese]="固定列を解除" },
        ["AutoSizeColumn"] = new() { [GridlyLanguage.Turkish]="Kolon genişliğini otomatik ayarla", [GridlyLanguage.English]="Auto size column", [GridlyLanguage.German]="Spaltenbreite automatisch", [GridlyLanguage.French]="Ajuster la colonne", [GridlyLanguage.Spanish]="Autoajustar columna", [GridlyLanguage.Italian]="Adatta colonna", [GridlyLanguage.Russian]="Автоширина столбца", [GridlyLanguage.Arabic]="ضبط عرض العمود تلقائياً", [GridlyLanguage.Chinese]="自动调整列宽", [GridlyLanguage.Japanese]="列幅を自動調整" },
        ["AutoSizeAllColumns"] = new() { [GridlyLanguage.Turkish]="Tüm kolonları otomatik sığdır", [GridlyLanguage.English]="Auto size all columns", [GridlyLanguage.German]="Alle Spalten automatisch anpassen", [GridlyLanguage.French]="Ajuster toutes les colonnes", [GridlyLanguage.Spanish]="Autoajustar todas las columnas", [GridlyLanguage.Italian]="Adatta tutte le colonne", [GridlyLanguage.Russian]="Автоширина всех столбцов", [GridlyLanguage.Arabic]="ضبط كل الأعمدة تلقائياً", [GridlyLanguage.Chinese]="自动调整所有列", [GridlyLanguage.Japanese]="すべての列幅を自動調整" },
        ["SaveColumnLayout"] = new() { [GridlyLanguage.Turkish]="Kolon düzenini kaydet", [GridlyLanguage.English]="Save column layout", [GridlyLanguage.German]="Spaltenlayout speichern", [GridlyLanguage.French]="Enregistrer la disposition", [GridlyLanguage.Spanish]="Guardar diseño de columnas", [GridlyLanguage.Italian]="Salva layout colonne", [GridlyLanguage.Russian]="Сохранить порядок столбцов", [GridlyLanguage.Arabic]="حفظ تخطيط الأعمدة", [GridlyLanguage.Chinese]="保存列布局", [GridlyLanguage.Japanese]="列レイアウトを保存" },
        ["LoadColumnLayout"] = new() { [GridlyLanguage.Turkish]="Kolon düzenini yükle", [GridlyLanguage.English]="Load column layout", [GridlyLanguage.German]="Spaltenlayout laden", [GridlyLanguage.French]="Charger la disposition", [GridlyLanguage.Spanish]="Cargar diseño de columnas", [GridlyLanguage.Italian]="Carica layout colonne", [GridlyLanguage.Russian]="Загрузить порядок столбцов", [GridlyLanguage.Arabic]="تحميل تخطيط الأعمدة", [GridlyLanguage.Chinese]="加载列布局", [GridlyLanguage.Japanese]="列レイアウトを読み込み" },
        ["ResetColumnLayout"] = new() { [GridlyLanguage.Turkish]="Kolon düzenini sıfırla", [GridlyLanguage.English]="Reset column layout", [GridlyLanguage.German]="Spaltenlayout zurücksetzen", [GridlyLanguage.French]="Réinitialiser la disposition", [GridlyLanguage.Spanish]="Restablecer diseño de columnas", [GridlyLanguage.Italian]="Reimposta layout colonne", [GridlyLanguage.Russian]="Сбросить порядок столбцов", [GridlyLanguage.Arabic]="إعادة ضبط تخطيط الأعمدة", [GridlyLanguage.Chinese]="重置列布局", [GridlyLanguage.Japanese]="列レイアウトをリセット" },
        ["ColumnChooserTitle"] = new() { [GridlyLanguage.Turkish]="Kolon Seçici", [GridlyLanguage.English]="Column chooser", [GridlyLanguage.German]="Spaltenauswahl", [GridlyLanguage.French]="Sélecteur de colonnes", [GridlyLanguage.Spanish]="Selector de columnas", [GridlyLanguage.Italian]="Selettore colonne", [GridlyLanguage.Russian]="Выбор столбцов", [GridlyLanguage.Arabic]="اختيار الأعمدة", [GridlyLanguage.Chinese]="列选择器", [GridlyLanguage.Japanese]="列の選択" },
        ["OK"] = new() { [GridlyLanguage.Turkish]="Tamam", [GridlyLanguage.English]="OK", [GridlyLanguage.German]="OK", [GridlyLanguage.French]="OK", [GridlyLanguage.Spanish]="Aceptar", [GridlyLanguage.Italian]="OK", [GridlyLanguage.Russian]="OK", [GridlyLanguage.Arabic]="موافق", [GridlyLanguage.Chinese]="确定", [GridlyLanguage.Japanese]="OK" },
        ["FastPreviewInfo"] = new() { [GridlyLanguage.Turkish]="Hızlı önizleme; yazılan filtre tüm kayıtlara uygulanır.", [GridlyLanguage.English]="Fast preview; typed filter applies to all rows.", [GridlyLanguage.German]="Schnellvorschau; Textfilter gilt für alle Zeilen.", [GridlyLanguage.French]="Aperçu rapide ; le texte filtre toutes les lignes.", [GridlyLanguage.Spanish]="Vista rápida; el texto filtra todas las filas.", [GridlyLanguage.Italian]="Anteprima rapida; il testo filtra tutte le righe.", [GridlyLanguage.Russian]="Быстрый просмотр; текстовый фильтр применяется ко всем строкам.", [GridlyLanguage.Arabic]="معاينة سريعة؛ النص يصفّي كل الصفوف.", [GridlyLanguage.Chinese]="快速预览；输入筛选应用于所有行。", [GridlyLanguage.Japanese]="高速プレビュー。入力フィルターは全行に適用。" },
        ["GroupByColumnPrefix"] = new() { [GridlyLanguage.Turkish]="Bu kolona göre grupla:", [GridlyLanguage.English]="Group by this column:", [GridlyLanguage.German]="Nach dieser Spalte gruppieren:", [GridlyLanguage.French]="Regrouper par cette colonne :", [GridlyLanguage.Spanish]="Agrupar por esta columna:", [GridlyLanguage.Italian]="Raggruppa per questa colonna:", [GridlyLanguage.Russian]="Группировать по столбцу:", [GridlyLanguage.Arabic]="تجميع حسب هذا العمود:", [GridlyLanguage.Chinese]="按此列分组:", [GridlyLanguage.Japanese]="この列でグループ化:" },
        ["CollapseAllGroups"] = new() { [GridlyLanguage.Turkish]="Tüm grupları daralt", [GridlyLanguage.English]="Collapse all groups", [GridlyLanguage.German]="Alle Gruppen einklappen", [GridlyLanguage.French]="Réduire tous les groupes", [GridlyLanguage.Spanish]="Contraer todos los grupos", [GridlyLanguage.Italian]="Comprimi tutti i gruppi", [GridlyLanguage.Russian]="Свернуть группы", [GridlyLanguage.Arabic]="طي كل المجموعات", [GridlyLanguage.Chinese]="折叠所有分组", [GridlyLanguage.Japanese]="すべてのグループを折りたたむ" },
        ["ExpandAllGroups"] = new() { [GridlyLanguage.Turkish]="Tüm grupları aç", [GridlyLanguage.English]="Expand all groups", [GridlyLanguage.German]="Alle Gruppen ausklappen", [GridlyLanguage.French]="Développer tous les groupes", [GridlyLanguage.Spanish]="Expandir todos los grupos", [GridlyLanguage.Italian]="Espandi tutti i gruppi", [GridlyLanguage.Russian]="Развернуть группы", [GridlyLanguage.Arabic]="فتح كل المجموعات", [GridlyLanguage.Chinese]="展开所有分组", [GridlyLanguage.Japanese]="すべてのグループを展開" },
        ["ClearGrouping"] = new() { [GridlyLanguage.Turkish]="Gruplamayı kaldır", [GridlyLanguage.English]="Clear grouping", [GridlyLanguage.German]="Gruppierung entfernen", [GridlyLanguage.French]="Effacer le regroupement", [GridlyLanguage.Spanish]="Quitar agrupación", [GridlyLanguage.Italian]="Rimuovi raggruppamento", [GridlyLanguage.Russian]="Убрать группировку", [GridlyLanguage.Arabic]="إزالة التجميع", [GridlyLanguage.Chinese]="清除分组", [GridlyLanguage.Japanese]="グループ化を解除" },
        ["CollapseThisGroup"] = new() { [GridlyLanguage.Turkish]="Bu grubu daralt", [GridlyLanguage.English]="Collapse this group", [GridlyLanguage.German]="Diese Gruppe einklappen", [GridlyLanguage.French]="Réduire ce groupe", [GridlyLanguage.Spanish]="Contraer este grupo", [GridlyLanguage.Italian]="Comprimi questo gruppo", [GridlyLanguage.Russian]="Свернуть эту группу", [GridlyLanguage.Arabic]="طي هذه المجموعة", [GridlyLanguage.Chinese]="折叠此分组", [GridlyLanguage.Japanese]="このグループを折りたたむ" },
        ["ExpandThisGroup"] = new() { [GridlyLanguage.Turkish]="Bu grubu aç", [GridlyLanguage.English]="Expand this group", [GridlyLanguage.German]="Diese Gruppe ausklappen", [GridlyLanguage.French]="Développer ce groupe", [GridlyLanguage.Spanish]="Expandir este grupo", [GridlyLanguage.Italian]="Espandi questo gruppo", [GridlyLanguage.Russian]="Развернуть эту группу", [GridlyLanguage.Arabic]="فتح هذه المجموعة", [GridlyLanguage.Chinese]="展开此分组", [GridlyLanguage.Japanese]="このグループを展開" },
        ["ShowOnlyThisGroup"] = new() { [GridlyLanguage.Turkish]="Sadece bu grubu açık bırak", [GridlyLanguage.English]="Keep only this group open", [GridlyLanguage.German]="Nur diese Gruppe offen lassen", [GridlyLanguage.French]="Garder seulement ce groupe ouvert", [GridlyLanguage.Spanish]="Dejar abierto solo este grupo", [GridlyLanguage.Italian]="Lascia aperto solo questo gruppo", [GridlyLanguage.Russian]="Оставить открытой только эту группу", [GridlyLanguage.Arabic]="إبقاء هذه المجموعة فقط مفتوحة", [GridlyLanguage.Chinese]="仅保持此分组展开", [GridlyLanguage.Japanese]="このグループだけ開いたままにする" },
        ["ViewMode"] = new() { [GridlyLanguage.Turkish]="Görünüm modu", [GridlyLanguage.English]="View mode", [GridlyLanguage.German]="Ansichtsmodus", [GridlyLanguage.French]="Mode d'affichage", [GridlyLanguage.Spanish]="Modo de vista", [GridlyLanguage.Italian]="Modalità vista", [GridlyLanguage.Russian]="Режим просмотра", [GridlyLanguage.Arabic]="نمط العرض", [GridlyLanguage.Chinese]="视图模式", [GridlyLanguage.Japanese]="表示モード" },
        ["ChooseColumns"] = new() { [GridlyLanguage.Turkish]="Kolonları seç...", [GridlyLanguage.English]="Choose columns...", [GridlyLanguage.German]="Spalten wählen...", [GridlyLanguage.French]="Choisir les colonnes...", [GridlyLanguage.Spanish]="Elegir columnas...", [GridlyLanguage.Italian]="Scegli colonne...", [GridlyLanguage.Russian]="Выбрать столбцы...", [GridlyLanguage.Arabic]="اختيار الأعمدة...", [GridlyLanguage.Chinese]="选择列...", [GridlyLanguage.Japanese]="列を選択..." },
        ["ClearFilters"] = new() { [GridlyLanguage.Turkish]="Filtreleri Temizle", [GridlyLanguage.English]="Clear Filters", [GridlyLanguage.German]="Filter löschen", [GridlyLanguage.French]="Effacer les filtres", [GridlyLanguage.Spanish]="Borrar filtros", [GridlyLanguage.Italian]="Cancella filtri", [GridlyLanguage.Russian]="Очистить фильтры", [GridlyLanguage.Arabic]="مسح عوامل التصفية", [GridlyLanguage.Chinese]="清除筛选", [GridlyLanguage.Japanese]="フィルターをクリア" },
        ["ClearAllFilters"] = new() { [GridlyLanguage.Turkish]="Tüm filtreleri temizle", [GridlyLanguage.English]="Clear all filters", [GridlyLanguage.German]="Alle Filter löschen", [GridlyLanguage.French]="Effacer tous les filtres", [GridlyLanguage.Spanish]="Borrar todos los filtros", [GridlyLanguage.Italian]="Cancella tutti i filtri", [GridlyLanguage.Russian]="Очистить все фильтры", [GridlyLanguage.Arabic]="مسح كل عوامل التصفية", [GridlyLanguage.Chinese]="清除所有筛选", [GridlyLanguage.Japanese]="すべてのフィルターをクリア" },
        ["SearchPlaceholder"] = new() { [GridlyLanguage.Turkish]="Aranacak / filtrelenecek değer...", [GridlyLanguage.English]="Search / filter value...", [GridlyLanguage.German]="Such-/Filterwert...", [GridlyLanguage.French]="Valeur à rechercher / filtrer...", [GridlyLanguage.Spanish]="Valor a buscar / filtrar...", [GridlyLanguage.Italian]="Valore da cercare / filtrare...", [GridlyLanguage.Russian]="Поиск / значение фильтра...", [GridlyLanguage.Arabic]="قيمة البحث / التصفية...", [GridlyLanguage.Chinese]="搜索 / 筛选值...", [GridlyLanguage.Japanese]="検索 / フィルター値..." },
        ["ApplyTypedTextAsFilter"] = new() { [GridlyLanguage.Turkish]="Yazılan metni filtre olarak uygula", [GridlyLanguage.English]="Apply typed text as filter", [GridlyLanguage.German]="Eingabetext als Filter verwenden", [GridlyLanguage.French]="Appliquer le texte saisi comme filtre", [GridlyLanguage.Spanish]="Aplicar texto escrito como filtro", [GridlyLanguage.Italian]="Usa il testo come filtro", [GridlyLanguage.Russian]="Применить введенный текст", [GridlyLanguage.Arabic]="تطبيق النص المكتوب كتصفية", [GridlyLanguage.Chinese]="将输入文本作为筛选", [GridlyLanguage.Japanese]="入力テキストをフィルターに適用" },
        ["SearchTypedTextInColumn"] = new() { [GridlyLanguage.Turkish]="Yazılan metni kolonda ara", [GridlyLanguage.English]="Search typed text in column", [GridlyLanguage.German]="Text in Spalte suchen", [GridlyLanguage.French]="Chercher le texte dans la colonne", [GridlyLanguage.Spanish]="Buscar texto en la columna", [GridlyLanguage.Italian]="Cerca testo nella colonna", [GridlyLanguage.Russian]="Искать текст в столбце", [GridlyLanguage.Arabic]="البحث عن النص في العمود", [GridlyLanguage.Chinese]="在列中搜索输入文本", [GridlyLanguage.Japanese]="列内で入力テキストを検索" },
        ["SelectAll"] = new() { [GridlyLanguage.Turkish]="Tümünü seç", [GridlyLanguage.English]="Select All", [GridlyLanguage.German]="Alle auswählen", [GridlyLanguage.French]="Tout sélectionner", [GridlyLanguage.Spanish]="Seleccionar todo", [GridlyLanguage.Italian]="Seleziona tutto", [GridlyLanguage.Russian]="Выбрать все", [GridlyLanguage.Arabic]="تحديد الكل", [GridlyLanguage.Chinese]="全选", [GridlyLanguage.Japanese]="すべて選択" },
        ["Apply"] = new() { [GridlyLanguage.Turkish]="Uygula", [GridlyLanguage.English]="Apply", [GridlyLanguage.German]="Anwenden", [GridlyLanguage.French]="Appliquer", [GridlyLanguage.Spanish]="Aplicar", [GridlyLanguage.Italian]="Applica", [GridlyLanguage.Russian]="Применить", [GridlyLanguage.Arabic]="تطبيق", [GridlyLanguage.Chinese]="应用", [GridlyLanguage.Japanese]="適用" },
        ["Clear"] = new() { [GridlyLanguage.Turkish]="Temizle", [GridlyLanguage.English]="Clear", [GridlyLanguage.German]="Löschen", [GridlyLanguage.French]="Effacer", [GridlyLanguage.Spanish]="Limpiar", [GridlyLanguage.Italian]="Cancella", [GridlyLanguage.Russian]="Очистить", [GridlyLanguage.Arabic]="مسح", [GridlyLanguage.Chinese]="清除", [GridlyLanguage.Japanese]="クリア" },
        ["SeparateFilterWindow"] = new() { [GridlyLanguage.Turkish]="Ayrı filtre penceresi...", [GridlyLanguage.English]="Separate filter window...", [GridlyLanguage.German]="Separates Filterfenster...", [GridlyLanguage.French]="Fenêtre de filtre séparée...", [GridlyLanguage.Spanish]="Ventana de filtro separada...", [GridlyLanguage.Italian]="Finestra filtro separata...", [GridlyLanguage.Russian]="Отдельное окно фильтра...", [GridlyLanguage.Arabic]="نافذة تصفية منفصلة...", [GridlyLanguage.Chinese]="单独筛选窗口...", [GridlyLanguage.Japanese]="別のフィルターウィンドウ..." },
        ["EmptyList"] = new() { [GridlyLanguage.Turkish]="Liste boş", [GridlyLanguage.English]="List is empty", [GridlyLanguage.German]="Liste ist leer", [GridlyLanguage.French]="La liste est vide", [GridlyLanguage.Spanish]="La lista está vacía", [GridlyLanguage.Italian]="La lista è vuota", [GridlyLanguage.Russian]="Список пуст", [GridlyLanguage.Arabic]="القائمة فارغة", [GridlyLanguage.Chinese]="列表为空", [GridlyLanguage.Japanese]="リストは空です" },

        ["ColumnFilterSuffix"] = new() { [GridlyLanguage.Turkish]="filtresi", [GridlyLanguage.English]="filter", [GridlyLanguage.German]="Filter", [GridlyLanguage.French]="filtre", [GridlyLanguage.Spanish]="filtro", [GridlyLanguage.Italian]="filtro", [GridlyLanguage.Russian]="фильтр", [GridlyLanguage.Arabic]="تصفية", [GridlyLanguage.Chinese]="筛选", [GridlyLanguage.Japanese]="フィルター" },
        ["FilterWindowSuffix"] = new() { [GridlyLanguage.Turkish]="filtre penceresi...", [GridlyLanguage.English]="filter window...", [GridlyLanguage.German]="Filterfenster...", [GridlyLanguage.French]="fenêtre de filtre...", [GridlyLanguage.Spanish]="ventana de filtro...", [GridlyLanguage.Italian]="finestra filtro...", [GridlyLanguage.Russian]="окно фильтра...", [GridlyLanguage.Arabic]="نافذة التصفية...", [GridlyLanguage.Chinese]="筛选窗口...", [GridlyLanguage.Japanese]="フィルターウィンドウ..." },
        ["EmptyValue"] = new() { [GridlyLanguage.Turkish]="(Boş)", [GridlyLanguage.English]="(Empty)", [GridlyLanguage.German]="(Leer)", [GridlyLanguage.French]="(Vide)", [GridlyLanguage.Spanish]="(Vacío)", [GridlyLanguage.Italian]="(Vuoto)", [GridlyLanguage.Russian]="(Пусто)", [GridlyLanguage.Arabic]="(فارغ)", [GridlyLanguage.Chinese]="(空)", [GridlyLanguage.Japanese]="(空)" },
        ["Copy"] = new() { [GridlyLanguage.Turkish]="Kopyala", [GridlyLanguage.English]="Copy", [GridlyLanguage.German]="Kopieren", [GridlyLanguage.French]="Copier", [GridlyLanguage.Spanish]="Copiar", [GridlyLanguage.Italian]="Copia", [GridlyLanguage.Russian]="Копировать", [GridlyLanguage.Arabic]="نسخ", [GridlyLanguage.Chinese]="复制", [GridlyLanguage.Japanese]="コピー" },
        ["Paste"] = new() { [GridlyLanguage.Turkish]="Yapıştır", [GridlyLanguage.English]="Paste", [GridlyLanguage.German]="Einfügen", [GridlyLanguage.French]="Coller", [GridlyLanguage.Spanish]="Pegar", [GridlyLanguage.Italian]="Incolla", [GridlyLanguage.Russian]="Вставить", [GridlyLanguage.Arabic]="لصق", [GridlyLanguage.Chinese]="粘贴", [GridlyLanguage.Japanese]="貼り付け" },
        ["EditCell"] = new() { [GridlyLanguage.Turkish]="Hücreyi Düzenle", [GridlyLanguage.English]="Edit cell", [GridlyLanguage.German]="Zelle bearbeiten", [GridlyLanguage.French]="Modifier la cellule", [GridlyLanguage.Spanish]="Editar celda", [GridlyLanguage.Italian]="Modifica cella", [GridlyLanguage.Russian]="Редактировать ячейку", [GridlyLanguage.Arabic]="تحرير الخلية", [GridlyLanguage.Chinese]="编辑单元格", [GridlyLanguage.Japanese]="セルを編集" },
        ["RowDetails"] = new() { [GridlyLanguage.Turkish]="Satır Detayı", [GridlyLanguage.English]="Row details", [GridlyLanguage.German]="Zeilendetails", [GridlyLanguage.French]="Détails de ligne", [GridlyLanguage.Spanish]="Detalles de fila", [GridlyLanguage.Italian]="Dettagli riga", [GridlyLanguage.Russian]="Детали строки", [GridlyLanguage.Arabic]="تفاصيل الصف", [GridlyLanguage.Chinese]="行详情", [GridlyLanguage.Japanese]="行の詳細" },
        ["PopupMenu"] = new() { [GridlyLanguage.Turkish]="Popup menü", [GridlyLanguage.English]="Popup menu", [GridlyLanguage.German]="Popup-Menü", [GridlyLanguage.French]="Menu popup", [GridlyLanguage.Spanish]="Menú emergente", [GridlyLanguage.Italian]="Menu popup", [GridlyLanguage.Russian]="Всплывающее меню", [GridlyLanguage.Arabic]="قائمة منبثقة", [GridlyLanguage.Chinese]="弹出菜单", [GridlyLanguage.Japanese]="ポップアップメニュー" },
        ["ModalWindow"] = new() { [GridlyLanguage.Turkish]="Ayrı pencere", [GridlyLanguage.English]="Separate window", [GridlyLanguage.German]="Separates Fenster", [GridlyLanguage.French]="Fenêtre séparée", [GridlyLanguage.Spanish]="Ventana separada", [GridlyLanguage.Italian]="Finestra separata", [GridlyLanguage.Russian]="Отдельное окно", [GridlyLanguage.Arabic]="نافذة منفصلة", [GridlyLanguage.Chinese]="独立窗口", [GridlyLanguage.Japanese]="別ウィンドウ" },
        ["Both"] = new() { [GridlyLanguage.Turkish]="İkisi birlikte", [GridlyLanguage.English]="Both", [GridlyLanguage.German]="Beide", [GridlyLanguage.French]="Les deux", [GridlyLanguage.Spanish]="Ambos", [GridlyLanguage.Italian]="Entrambi", [GridlyLanguage.Russian]="Оба", [GridlyLanguage.Arabic]="كلاهما", [GridlyLanguage.Chinese]="两者", [GridlyLanguage.Japanese]="両方" },
        ["ExtraLarge"] = new() { [GridlyLanguage.Turkish]="Kompakt", [GridlyLanguage.English]="Extra large", [GridlyLanguage.German]="Sehr groß", [GridlyLanguage.French]="Très grand", [GridlyLanguage.Spanish]="Muy grande", [GridlyLanguage.Italian]="Molto grande", [GridlyLanguage.Russian]="Очень крупный", [GridlyLanguage.Arabic]="كبير جداً", [GridlyLanguage.Chinese]="超大", [GridlyLanguage.Japanese]="特大" },
        ["Large"] = new() { [GridlyLanguage.Turkish]="Standart", [GridlyLanguage.English]="Large", [GridlyLanguage.German]="Groß", [GridlyLanguage.French]="Grand", [GridlyLanguage.Spanish]="Grande", [GridlyLanguage.Italian]="Grande", [GridlyLanguage.Russian]="Крупный", [GridlyLanguage.Arabic]="كبير", [GridlyLanguage.Chinese]="大", [GridlyLanguage.Japanese]="大" },
        ["Medium"] = new() { [GridlyLanguage.Turkish]="Geniş", [GridlyLanguage.English]="Medium", [GridlyLanguage.German]="Mittel", [GridlyLanguage.French]="Moyen", [GridlyLanguage.Spanish]="Medio", [GridlyLanguage.Italian]="Medio", [GridlyLanguage.Russian]="Средний", [GridlyLanguage.Arabic]="متوسط", [GridlyLanguage.Chinese]="中", [GridlyLanguage.Japanese]="中" },
        ["List"] = new() { [GridlyLanguage.Turkish]="Liste", [GridlyLanguage.English]="List", [GridlyLanguage.German]="Liste", [GridlyLanguage.French]="Liste", [GridlyLanguage.Spanish]="Lista", [GridlyLanguage.Italian]="Lista", [GridlyLanguage.Russian]="Список", [GridlyLanguage.Arabic]="قائمة", [GridlyLanguage.Chinese]="列表", [GridlyLanguage.Japanese]="リスト" },
        ["Details"] = new() { [GridlyLanguage.Turkish]="Detay", [GridlyLanguage.English]="Details", [GridlyLanguage.German]="Details", [GridlyLanguage.French]="Détails", [GridlyLanguage.Spanish]="Detalles", [GridlyLanguage.Italian]="Dettagli", [GridlyLanguage.Russian]="Подробности", [GridlyLanguage.Arabic]="تفاصيل", [GridlyLanguage.Chinese]="详细信息", [GridlyLanguage.Japanese]="詳細" },
        ["Tiles"] = new() { [GridlyLanguage.Turkish]="Kart", [GridlyLanguage.English]="Tile / Card", [GridlyLanguage.German]="Kachel / Karte", [GridlyLanguage.French]="Tuile / Carte", [GridlyLanguage.Spanish]="Mosaico / Tarjeta", [GridlyLanguage.Italian]="Riquadro / Scheda", [GridlyLanguage.Russian]="Плитка / Карточка", [GridlyLanguage.Arabic]="بطاقة / مربع", [GridlyLanguage.Chinese]="磁贴 / 卡片", [GridlyLanguage.Japanese]="タイル / カード" },

        ["Columns"] = new() { [GridlyLanguage.Turkish]="Kolonlar", [GridlyLanguage.English]="Columns", [GridlyLanguage.German]="Spalten", [GridlyLanguage.French]="Colonnes", [GridlyLanguage.Spanish]="Columnas", [GridlyLanguage.Italian]="Colonne", [GridlyLanguage.Russian]="Столбцы", [GridlyLanguage.Arabic]="الأعمدة", [GridlyLanguage.Chinese]="列", [GridlyLanguage.Japanese]="列" },
        ["ShowAll"] = new() { [GridlyLanguage.Turkish]="Tümünü göster", [GridlyLanguage.English]="Show all", [GridlyLanguage.German]="Alle anzeigen", [GridlyLanguage.French]="Tout afficher", [GridlyLanguage.Spanish]="Mostrar todo", [GridlyLanguage.Italian]="Mostra tutto", [GridlyLanguage.Russian]="Показать все", [GridlyLanguage.Arabic]="إظهار الكل", [GridlyLanguage.Chinese]="全部显示", [GridlyLanguage.Japanese]="すべて表示" },
        ["HideAll"] = new() { [GridlyLanguage.Turkish]="Tümünü gizle", [GridlyLanguage.English]="Hide all", [GridlyLanguage.German]="Alle ausblenden", [GridlyLanguage.French]="Tout masquer", [GridlyLanguage.Spanish]="Ocultar todo", [GridlyLanguage.Italian]="Nascondi tutto", [GridlyLanguage.Russian]="Скрыть все", [GridlyLanguage.Arabic]="إخفاء الكل", [GridlyLanguage.Chinese]="全部隐藏", [GridlyLanguage.Japanese]="すべて非表示" },
        ["DefaultColumnLayout"] = new() { [GridlyLanguage.Turkish]="Varsayılan kolon düzeni", [GridlyLanguage.English]="Default column layout", [GridlyLanguage.German]="Standard-Spaltenlayout", [GridlyLanguage.French]="Disposition de colonnes par défaut", [GridlyLanguage.Spanish]="Diseño de columnas predeterminado", [GridlyLanguage.Italian]="Layout colonne predefinito", [GridlyLanguage.Russian]="Стандартный порядок столбцов", [GridlyLanguage.Arabic]="تخطيط الأعمدة الافتراضي", [GridlyLanguage.Chinese]="默认列布局", [GridlyLanguage.Japanese]="既定の列レイアウト" },
        ["FitVisibleColumns"] = new() { [GridlyLanguage.Turkish]="Görünür kolonları sığdır", [GridlyLanguage.English]="Fit visible columns", [GridlyLanguage.German]="Sichtbare Spalten anpassen", [GridlyLanguage.French]="Ajuster les colonnes visibles", [GridlyLanguage.Spanish]="Ajustar columnas visibles", [GridlyLanguage.Italian]="Adatta colonne visibili", [GridlyLanguage.Russian]="Подогнать видимые столбцы", [GridlyLanguage.Arabic]="ملاءمة الأعمدة المرئية", [GridlyLanguage.Chinese]="适应可见列", [GridlyLanguage.Japanese]="表示列を合わせる" },
        ["ColumnChooserWindow"] = new() { [GridlyLanguage.Turkish]="Kolon seçici penceresi...", [GridlyLanguage.English]="Column chooser window...", [GridlyLanguage.German]="Spaltenauswahlfenster...", [GridlyLanguage.French]="Fenêtre de sélection des colonnes...", [GridlyLanguage.Spanish]="Ventana de selección de columnas...", [GridlyLanguage.Italian]="Finestra selettore colonne...", [GridlyLanguage.Russian]="Окно выбора столбцов...", [GridlyLanguage.Arabic]="نافذة اختيار الأعمدة...", [GridlyLanguage.Chinese]="列选择窗口...", [GridlyLanguage.Japanese]="列選択ウィンドウ..." },
        ["ColumnSearchPlaceholder"] = new() { [GridlyLanguage.Turkish]="Kolon ara...", [GridlyLanguage.English]="Search columns...", [GridlyLanguage.German]="Spalten suchen...", [GridlyLanguage.French]="Rechercher des colonnes...", [GridlyLanguage.Spanish]="Buscar columnas...", [GridlyLanguage.Italian]="Cerca colonne...", [GridlyLanguage.Russian]="Поиск столбцов...", [GridlyLanguage.Arabic]="بحث في الأعمدة...", [GridlyLanguage.Chinese]="搜索列...", [GridlyLanguage.Japanese]="列を検索..." },
        ["Cancel"] = new() { [GridlyLanguage.Turkish]="İptal", [GridlyLanguage.English]="Cancel", [GridlyLanguage.German]="Abbrechen", [GridlyLanguage.French]="Annuler", [GridlyLanguage.Spanish]="Cancelar", [GridlyLanguage.Italian]="Annulla", [GridlyLanguage.Russian]="Отмена", [GridlyLanguage.Arabic]="إلغاء", [GridlyLanguage.Chinese]="取消", [GridlyLanguage.Japanese]="キャンセル" },
        ["ClearColumnFilter"] = new() { [GridlyLanguage.Turkish]="Bu kolonun filtresini temizle", [GridlyLanguage.English]="Clear this column filter", [GridlyLanguage.German]="Filter dieser Spalte löschen", [GridlyLanguage.French]="Effacer le filtre de cette colonne", [GridlyLanguage.Spanish]="Borrar filtro de esta columna", [GridlyLanguage.Italian]="Cancella filtro colonna", [GridlyLanguage.Russian]="Очистить фильтр столбца", [GridlyLanguage.Arabic]="مسح فلتر هذا العمود", [GridlyLanguage.Chinese]="清除此列筛选", [GridlyLanguage.Japanese]="この列のフィルターをクリア" },
        ["CopyCell"] = new() { [GridlyLanguage.Turkish]="Hücreyi kopyala", [GridlyLanguage.English]="Copy cell", [GridlyLanguage.German]="Zelle kopieren", [GridlyLanguage.French]="Copier la cellule", [GridlyLanguage.Spanish]="Copiar celda", [GridlyLanguage.Italian]="Copia cella", [GridlyLanguage.Russian]="Копировать ячейку", [GridlyLanguage.Arabic]="نسخ الخلية", [GridlyLanguage.Chinese]="复制单元格", [GridlyLanguage.Japanese]="セルをコピー" },
        ["CopySelectionJson"] = new() { [GridlyLanguage.Turkish]="Seçimi JSON kopyala", [GridlyLanguage.English]="Copy selection as JSON", [GridlyLanguage.German]="Auswahl als JSON kopieren", [GridlyLanguage.French]="Copier la sélection en JSON", [GridlyLanguage.Spanish]="Copiar selección como JSON", [GridlyLanguage.Italian]="Copia selezione come JSON", [GridlyLanguage.Russian]="Копировать выбор как JSON", [GridlyLanguage.Arabic]="نسخ التحديد كـ JSON", [GridlyLanguage.Chinese]="复制选择为 JSON", [GridlyLanguage.Japanese]="選択をJSONでコピー" },
        ["CopyMiniAnalytics"] = new() { [GridlyLanguage.Turkish]="Mini analytics kopyala", [GridlyLanguage.English]="Copy mini analytics", [GridlyLanguage.German]="Mini-Analyse kopieren", [GridlyLanguage.French]="Copier la mini-analyse", [GridlyLanguage.Spanish]="Copiar mini análisis", [GridlyLanguage.Italian]="Copia mini analisi", [GridlyLanguage.Russian]="Копировать мини-аналитику", [GridlyLanguage.Arabic]="نسخ التحليل المصغر", [GridlyLanguage.Chinese]="复制迷你分析", [GridlyLanguage.Japanese]="ミニ分析をコピー" },
        ["Mode"] = new() { [GridlyLanguage.Turkish]="Çalışma modu", [GridlyLanguage.English]="Mode", [GridlyLanguage.German]="Modus", [GridlyLanguage.French]="Mode", [GridlyLanguage.Spanish]="Modo", [GridlyLanguage.Italian]="Modalità", [GridlyLanguage.Russian]="Режим", [GridlyLanguage.Arabic]="الوضع", [GridlyLanguage.Chinese]="模式", [GridlyLanguage.Japanese]="モード" },
        ["Theme"] = new() { [GridlyLanguage.Turkish]="Tema", [GridlyLanguage.English]="Theme", [GridlyLanguage.German]="Design", [GridlyLanguage.French]="Thème", [GridlyLanguage.Spanish]="Tema", [GridlyLanguage.Italian]="Tema", [GridlyLanguage.Russian]="Тема", [GridlyLanguage.Arabic]="السمة", [GridlyLanguage.Chinese]="主题", [GridlyLanguage.Japanese]="テーマ" },
        ["Sorting"] = new() { [GridlyLanguage.Turkish]="Sıralama", [GridlyLanguage.English]="Sorting", [GridlyLanguage.German]="Sortierung", [GridlyLanguage.French]="Tri", [GridlyLanguage.Spanish]="Ordenación", [GridlyLanguage.Italian]="Ordinamento", [GridlyLanguage.Russian]="Сортировка", [GridlyLanguage.Arabic]="الترتيب", [GridlyLanguage.Chinese]="排序", [GridlyLanguage.Japanese]="並べ替え" },
        ["FrozenColumn"] = new() { [GridlyLanguage.Turkish]="Sabit kolon", [GridlyLanguage.English]="Frozen column", [GridlyLanguage.German]="Fixierte Spalte", [GridlyLanguage.French]="Colonne figée", [GridlyLanguage.Spanish]="Columna fijada", [GridlyLanguage.Italian]="Colonna bloccata", [GridlyLanguage.Russian]="Закрепленный столбец", [GridlyLanguage.Arabic]="عمود مثبت", [GridlyLanguage.Chinese]="冻结列", [GridlyLanguage.Japanese]="固定列" },
        ["ColumnWidth"] = new() { [GridlyLanguage.Turkish]="Kolon genişliği", [GridlyLanguage.English]="Column width", [GridlyLanguage.German]="Spaltenbreite", [GridlyLanguage.French]="Largeur de colonne", [GridlyLanguage.Spanish]="Ancho de columna", [GridlyLanguage.Italian]="Larghezza colonna", [GridlyLanguage.Russian]="Ширина столбца", [GridlyLanguage.Arabic]="عرض العمود", [GridlyLanguage.Chinese]="列宽", [GridlyLanguage.Japanese]="列幅" },
        ["Layout"] = new() { [GridlyLanguage.Turkish]="Düzen", [GridlyLanguage.English]="Layout", [GridlyLanguage.German]="Layout", [GridlyLanguage.French]="Disposition", [GridlyLanguage.Spanish]="Diseño", [GridlyLanguage.Italian]="Layout", [GridlyLanguage.Russian]="Макет", [GridlyLanguage.Arabic]="التخطيط", [GridlyLanguage.Chinese]="布局", [GridlyLanguage.Japanese]="レイアウト" },
        ["SaveDefaultLayoutProfile"] = new() { [GridlyLanguage.Turkish]="Layout profilini kaydet: Default", [GridlyLanguage.English]="Save layout profile: Default", [GridlyLanguage.German]="Layoutprofil speichern: Default", [GridlyLanguage.French]="Enregistrer le profil : Default", [GridlyLanguage.Spanish]="Guardar perfil: Default", [GridlyLanguage.Italian]="Salva profilo: Default", [GridlyLanguage.Russian]="Сохранить профиль: Default", [GridlyLanguage.Arabic]="حفظ ملف التخطيط: Default", [GridlyLanguage.Chinese]="保存布局配置: Default", [GridlyLanguage.Japanese]="レイアウトプロファイル保存: Default" },
        ["LayoutProfiles"] = new() { [GridlyLanguage.Turkish]="Layout profilleri", [GridlyLanguage.English]="Layout profiles", [GridlyLanguage.German]="Layoutprofile", [GridlyLanguage.French]="Profils de disposition", [GridlyLanguage.Spanish]="Perfiles de diseño", [GridlyLanguage.Italian]="Profili layout", [GridlyLanguage.Russian]="Профили макета", [GridlyLanguage.Arabic]="ملفات التخطيط", [GridlyLanguage.Chinese]="布局配置", [GridlyLanguage.Japanese]="レイアウトプロファイル" },
        ["SaveUserLayout"] = new() { [GridlyLanguage.Turkish]="Kullanıcı düzenini kaydet", [GridlyLanguage.English]="Save user layout", [GridlyLanguage.German]="Benutzerlayout speichern", [GridlyLanguage.French]="Enregistrer la disposition utilisateur", [GridlyLanguage.Spanish]="Guardar diseño de usuario", [GridlyLanguage.Italian]="Salva layout utente", [GridlyLanguage.Russian]="Сохранить макет пользователя", [GridlyLanguage.Arabic]="حفظ تخطيط المستخدم", [GridlyLanguage.Chinese]="保存用户布局", [GridlyLanguage.Japanese]="ユーザーレイアウトを保存" },
        ["LoadUserLayout"] = new() { [GridlyLanguage.Turkish]="Kullanıcı düzenini yükle", [GridlyLanguage.English]="Load user layout", [GridlyLanguage.German]="Benutzerlayout laden", [GridlyLanguage.French]="Charger la disposition utilisateur", [GridlyLanguage.Spanish]="Cargar diseño de usuario", [GridlyLanguage.Italian]="Carica layout utente", [GridlyLanguage.Russian]="Загрузить макет пользователя", [GridlyLanguage.Arabic]="تحميل تخطيط المستخدم", [GridlyLanguage.Chinese]="加载用户布局", [GridlyLanguage.Japanese]="ユーザーレイアウトを読み込み" },
        ["ResetUserLayout"] = new() { [GridlyLanguage.Turkish]="Kullanıcı düzenini varsayılana döndür", [GridlyLanguage.English]="Reset user layout to default", [GridlyLanguage.German]="Benutzerlayout zurücksetzen", [GridlyLanguage.French]="Réinitialiser la disposition utilisateur", [GridlyLanguage.Spanish]="Restablecer diseño de usuario", [GridlyLanguage.Italian]="Reimposta layout utente", [GridlyLanguage.Russian]="Сбросить макет пользователя", [GridlyLanguage.Arabic]="إعادة ضبط تخطيط المستخدم", [GridlyLanguage.Chinese]="重置用户布局", [GridlyLanguage.Japanese]="ユーザーレイアウトをリセット" },
        ["ExportUserLayout"] = new() { [GridlyLanguage.Turkish]="Kullanıcı düzenini dışa aktar...", [GridlyLanguage.English]="Export user layout...", [GridlyLanguage.German]="Benutzerlayout exportieren...", [GridlyLanguage.French]="Exporter la disposition utilisateur...", [GridlyLanguage.Spanish]="Exportar diseño de usuario...", [GridlyLanguage.Italian]="Esporta layout utente...", [GridlyLanguage.Russian]="Экспорт макета пользователя...", [GridlyLanguage.Arabic]="تصدير تخطيط المستخدم...", [GridlyLanguage.Chinese]="导出用户布局...", [GridlyLanguage.Japanese]="ユーザーレイアウトを書き出し..." },
        ["ImportUserLayout"] = new() { [GridlyLanguage.Turkish]="Kullanıcı düzenini içe aktar...", [GridlyLanguage.English]="Import user layout...", [GridlyLanguage.German]="Benutzerlayout importieren...", [GridlyLanguage.French]="Importer la disposition utilisateur...", [GridlyLanguage.Spanish]="Importar diseño de usuario...", [GridlyLanguage.Italian]="Importa layout utente...", [GridlyLanguage.Russian]="Импорт макета пользователя...", [GridlyLanguage.Arabic]="استيراد تخطيط المستخدم...", [GridlyLanguage.Chinese]="导入用户布局...", [GridlyLanguage.Japanese]="ユーザーレイアウトを読み込み..." },
        ["Grouping"] = new() { [GridlyLanguage.Turkish]="Gruplama", [GridlyLanguage.English]="Grouping", [GridlyLanguage.German]="Gruppierung", [GridlyLanguage.French]="Regroupement", [GridlyLanguage.Spanish]="Agrupación", [GridlyLanguage.Italian]="Raggruppamento", [GridlyLanguage.Russian]="Группировка", [GridlyLanguage.Arabic]="التجميع", [GridlyLanguage.Chinese]="分组", [GridlyLanguage.Japanese]="グループ化" },
        ["Freeze"] = new() { [GridlyLanguage.Turkish]="Sabitleme", [GridlyLanguage.English]="Freeze", [GridlyLanguage.German]="Fixieren", [GridlyLanguage.French]="Figer", [GridlyLanguage.Spanish]="Fijar", [GridlyLanguage.Italian]="Blocca", [GridlyLanguage.Russian]="Закрепить", [GridlyLanguage.Arabic]="تثبيت", [GridlyLanguage.Chinese]="冻结", [GridlyLanguage.Japanese]="固定" },
        ["View"] = new() { [GridlyLanguage.Turkish]="Görünüm", [GridlyLanguage.English]="View", [GridlyLanguage.German]="Ansicht", [GridlyLanguage.French]="Vue", [GridlyLanguage.Spanish]="Vista", [GridlyLanguage.Italian]="Vista", [GridlyLanguage.Russian]="Вид", [GridlyLanguage.Arabic]="العرض", [GridlyLanguage.Chinese]="视图", [GridlyLanguage.Japanese]="表示" },
        ["Clipboard"] = new() { [GridlyLanguage.Turkish]="Pano", [GridlyLanguage.English]="Clipboard", [GridlyLanguage.German]="Zwischenablage", [GridlyLanguage.French]="Presse-papiers", [GridlyLanguage.Spanish]="Portapapeles", [GridlyLanguage.Italian]="Appunti", [GridlyLanguage.Russian]="Буфер обмена", [GridlyLanguage.Arabic]="الحافظة", [GridlyLanguage.Chinese]="剪贴板", [GridlyLanguage.Japanese]="クリップボード" },
        ["Editing"] = new() { [GridlyLanguage.Turkish]="Düzenleme", [GridlyLanguage.English]="Editing", [GridlyLanguage.German]="Bearbeiten", [GridlyLanguage.French]="Édition", [GridlyLanguage.Spanish]="Edición", [GridlyLanguage.Italian]="Modifica", [GridlyLanguage.Russian]="Редактирование", [GridlyLanguage.Arabic]="التحرير", [GridlyLanguage.Chinese]="编辑", [GridlyLanguage.Japanese]="編集" },
        ["Analytics"] = new() { [GridlyLanguage.Turkish]="Analiz", [GridlyLanguage.English]="Analytics", [GridlyLanguage.German]="Analyse", [GridlyLanguage.French]="Analyse", [GridlyLanguage.Spanish]="Análisis", [GridlyLanguage.Italian]="Analisi", [GridlyLanguage.Russian]="Аналитика", [GridlyLanguage.Arabic]="التحليلات", [GridlyLanguage.Chinese]="分析", [GridlyLanguage.Japanese]="分析" },
        ["BuiltInHeaderMenu"] = new() { [GridlyLanguage.Turkish]="Kolon / filtre özellikleri", [GridlyLanguage.English]="Column / filter options", [GridlyLanguage.German]="Spalten-/Filteroptionen", [GridlyLanguage.French]="Options colonne / filtre", [GridlyLanguage.Spanish]="Opciones de columna / filtro", [GridlyLanguage.Italian]="Opzioni colonna / filtro", [GridlyLanguage.Russian]="Параметры столбца / фильтра", [GridlyLanguage.Arabic]="خيارات العمود / التصفية", [GridlyLanguage.Chinese]="列 / 筛选选项", [GridlyLanguage.Japanese]="列 / フィルターオプション" },
        ["GridlyMode_Object"] = new() { [GridlyLanguage.Turkish]="Nesne", [GridlyLanguage.English]="Object", [GridlyLanguage.German]="Objekt", [GridlyLanguage.French]="Objet", [GridlyLanguage.Spanish]="Objeto", [GridlyLanguage.Italian]="Oggetto", [GridlyLanguage.Russian]="Объект", [GridlyLanguage.Arabic]="كائن", [GridlyLanguage.Chinese]="对象", [GridlyLanguage.Japanese]="オブジェクト" },
        ["GridlyMode_DataTable"] = new() { [GridlyLanguage.Turkish]="DataTable", [GridlyLanguage.English]="DataTable", [GridlyLanguage.German]="Datentabelle", [GridlyLanguage.French]="Table de données", [GridlyLanguage.Spanish]="Tabla de datos", [GridlyLanguage.Italian]="Tabella dati", [GridlyLanguage.Russian]="Таблица данных", [GridlyLanguage.Arabic]="جدول بيانات", [GridlyLanguage.Chinese]="数据表", [GridlyLanguage.Japanese]="データテーブル" },
        ["GridlyMode_Virtual"] = new() { [GridlyLanguage.Turkish]="Sanal", [GridlyLanguage.English]="Virtual", [GridlyLanguage.German]="Virtuell", [GridlyLanguage.French]="Virtuel", [GridlyLanguage.Spanish]="Virtual", [GridlyLanguage.Italian]="Virtuale", [GridlyLanguage.Russian]="Виртуальный", [GridlyLanguage.Arabic]="افتراضي", [GridlyLanguage.Chinese]="虚拟", [GridlyLanguage.Japanese]="仮想" },
        ["GridlyMode_Tree"] = new() { [GridlyLanguage.Turkish]="Ağaç", [GridlyLanguage.English]="Tree", [GridlyLanguage.German]="Baum", [GridlyLanguage.French]="Arbre", [GridlyLanguage.Spanish]="Árbol", [GridlyLanguage.Italian]="Albero", [GridlyLanguage.Russian]="Дерево", [GridlyLanguage.Arabic]="شجرة", [GridlyLanguage.Chinese]="树", [GridlyLanguage.Japanese]="ツリー" },
        ["GridlyMode_Tile"] = new() { [GridlyLanguage.Turkish]="Kart", [GridlyLanguage.English]="Tile", [GridlyLanguage.German]="Kachel", [GridlyLanguage.French]="Tuile", [GridlyLanguage.Spanish]="Mosaico", [GridlyLanguage.Italian]="Riquadro", [GridlyLanguage.Russian]="Плитка", [GridlyLanguage.Arabic]="بطاقة", [GridlyLanguage.Chinese]="磁贴", [GridlyLanguage.Japanese]="タイル" },
        ["Theme_System"] = new() { [GridlyLanguage.Turkish]="Sistem", [GridlyLanguage.English]="System", [GridlyLanguage.German]="System", [GridlyLanguage.French]="Système", [GridlyLanguage.Spanish]="Sistema", [GridlyLanguage.Italian]="Sistema", [GridlyLanguage.Russian]="Система", [GridlyLanguage.Arabic]="النظام", [GridlyLanguage.Chinese]="系统", [GridlyLanguage.Japanese]="システム" },
        ["Theme_Light"] = new() { [GridlyLanguage.Turkish]="Açık", [GridlyLanguage.English]="Light", [GridlyLanguage.German]="Hell", [GridlyLanguage.French]="Clair", [GridlyLanguage.Spanish]="Claro", [GridlyLanguage.Italian]="Chiaro", [GridlyLanguage.Russian]="Светлая", [GridlyLanguage.Arabic]="فاتح", [GridlyLanguage.Chinese]="浅色", [GridlyLanguage.Japanese]="ライト" },
        ["Theme_Dark"] = new() { [GridlyLanguage.Turkish]="Koyu", [GridlyLanguage.English]="Dark", [GridlyLanguage.German]="Dunkel", [GridlyLanguage.French]="Sombre", [GridlyLanguage.Spanish]="Oscuro", [GridlyLanguage.Italian]="Scuro", [GridlyLanguage.Russian]="Темная", [GridlyLanguage.Arabic]="داكن", [GridlyLanguage.Chinese]="深色", [GridlyLanguage.Japanese]="ダーク" },
        ["Theme_FluentLight"] = new() { [GridlyLanguage.Turkish]="Fluent Açık", [GridlyLanguage.English]="Fluent Light", [GridlyLanguage.German]="Fluent Hell", [GridlyLanguage.French]="Fluent clair", [GridlyLanguage.Spanish]="Fluent claro", [GridlyLanguage.Italian]="Fluent chiaro", [GridlyLanguage.Russian]="Fluent светлая", [GridlyLanguage.Arabic]="Fluent فاتح", [GridlyLanguage.Chinese]="Fluent 浅色", [GridlyLanguage.Japanese]="Fluent ライト" },
        ["Theme_FluentDark"] = new() { [GridlyLanguage.Turkish]="Fluent Koyu", [GridlyLanguage.English]="Fluent Dark", [GridlyLanguage.German]="Fluent Dunkel", [GridlyLanguage.French]="Fluent sombre", [GridlyLanguage.Spanish]="Fluent oscuro", [GridlyLanguage.Italian]="Fluent scuro", [GridlyLanguage.Russian]="Fluent темная", [GridlyLanguage.Arabic]="Fluent داكن", [GridlyLanguage.Chinese]="Fluent 深色", [GridlyLanguage.Japanese]="Fluent ダーク" },
        ["BuiltInMenuMergeText"] = new() { [GridlyLanguage.Turkish]="Liste özellikleri", [GridlyLanguage.English]="List options", [GridlyLanguage.German]="Listenoptionen", [GridlyLanguage.French]="Options de liste", [GridlyLanguage.Spanish]="Opciones de lista", [GridlyLanguage.Italian]="Opzioni elenco", [GridlyLanguage.Russian]="Параметры списка", [GridlyLanguage.Arabic]="خيارات القائمة", [GridlyLanguage.Chinese]="列表选项", [GridlyLanguage.Japanese]="リストオプション" },
        ["FastPreviewLimitedInfo"] = new() { [GridlyLanguage.Turkish]="İlk açılış hızlı önizlemedir. 3+ karakter yazınca tüm veri kaynağı arka planda taranır.", [GridlyLanguage.English]="First opening is a fast preview. Type 3+ characters to scan the full data source in the background.", [GridlyLanguage.German]="Beim ersten Öffnen wird eine Schnellvorschau angezeigt. Ab 3 Zeichen wird die gesamte Datenquelle im Hintergrund durchsucht.", [GridlyLanguage.French]="La première ouverture est un aperçu rapide. Tapez au moins 3 caractères pour analyser toute la source en arrière-plan.", [GridlyLanguage.Spanish]="La primera apertura es una vista rápida. Escriba 3+ caracteres para buscar en toda la fuente en segundo plano.", [GridlyLanguage.Italian]="La prima apertura è un'anteprima rapida. Digita almeno 3 caratteri per analizzare l'intera origine dati in background.", [GridlyLanguage.Russian]="Первое открытие — быстрый предпросмотр. Введите 3+ символа, чтобы просканировать весь источник данных в фоне.", [GridlyLanguage.Arabic]="الفتح الأول معاينة سريعة. اكتب 3 أحرف أو أكثر لفحص مصدر البيانات كاملاً في الخلفية.", [GridlyLanguage.Chinese]="首次打开为快速预览。输入 3 个以上字符将在后台扫描完整数据源。", [GridlyLanguage.Japanese]="初回表示は高速プレビューです。3文字以上入力すると全データソースをバックグラウンドで検索します。" },
        ["SearchingPreviewResults"] = new() { [GridlyLanguage.Turkish]="Aranıyor... Liste ilk sonuçları gösteriyor", [GridlyLanguage.English]="Searching... The list shows initial results", [GridlyLanguage.German]="Suche läuft... Die Liste zeigt erste Ergebnisse", [GridlyLanguage.French]="Recherche... La liste affiche les premiers résultats", [GridlyLanguage.Spanish]="Buscando... La lista muestra los primeros resultados", [GridlyLanguage.Italian]="Ricerca... L'elenco mostra i primi risultati", [GridlyLanguage.Russian]="Поиск... список показывает первые результаты", [GridlyLanguage.Arabic]="جارٍ البحث... تعرض القائمة النتائج الأولى", [GridlyLanguage.Chinese]="正在搜索... 列表显示初始结果", [GridlyLanguage.Japanese]="検索中... リストに初期結果を表示しています" },
        ["PrintPreviewSuffix"] = new() { [GridlyLanguage.Turkish]="Önizleme", [GridlyLanguage.English]="Preview", [GridlyLanguage.German]="Vorschau", [GridlyLanguage.French]="Aperçu", [GridlyLanguage.Spanish]="Vista previa", [GridlyLanguage.Italian]="Anteprima", [GridlyLanguage.Russian]="Предпросмотр", [GridlyLanguage.Arabic]="معاينة", [GridlyLanguage.Chinese]="预览", [GridlyLanguage.Japanese]="プレビュー" },
        ["Posters"] = new() { [GridlyLanguage.Turkish]="Poster / Resimli içerik", [GridlyLanguage.English]="Poster / Image content", [GridlyLanguage.German]="Poster / Bildinhalt", [GridlyLanguage.French]="Affiche / contenu image", [GridlyLanguage.Spanish]="Póster / contenido visual", [GridlyLanguage.Italian]="Poster / contenuto immagine", [GridlyLanguage.Russian]="Постер / изображение", [GridlyLanguage.Arabic]="ملصق / محتوى مرئي", [GridlyLanguage.Chinese]="海报 / 图片内容", [GridlyLanguage.Japanese]="ポスター / 画像コンテンツ" }
    };

    public static GridlyLanguage Language { get; set; } = GridlyLanguage.Auto;
    public static IDictionary<string, string> CustomTranslations { get; } = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);

    public static string GridlyModeName(string name)
    {
        string key = "GridlyMode_" + name;
        string value = T(key);
        return string.Equals(value, key, StringComparison.OrdinalIgnoreCase) ? name : value;
    }

    public static string ThemePresetName(string name)
    {
        string key = "Theme_" + name;
        string value = T(key);
        return string.Equals(value, key, StringComparison.OrdinalIgnoreCase) ? name : value;
    }

    public static void LoadCustomTranslations(string jsonFilePath)
    {
        if (!File.Exists(jsonFilePath)) return;
        var data = JsonSerializer.Deserialize<Dictionary<string, string>>(File.ReadAllText(jsonFilePath));
        if (data == null) return;
        foreach (var kv in data) CustomTranslations[kv.Key] = kv.Value;
    }

    public static GridlyLanguage EffectiveLanguage
    {
        get
        {
            if (Language != GridlyLanguage.Auto) return Language;
            var two = CultureInfo.CurrentUICulture.TwoLetterISOLanguageName.ToLowerInvariant();
            return two switch
            {
                "tr" => GridlyLanguage.Turkish,
                "de" => GridlyLanguage.German,
                "fr" => GridlyLanguage.French,
                "es" => GridlyLanguage.Spanish,
                "it" => GridlyLanguage.Italian,
                "ru" => GridlyLanguage.Russian,
                "ar" => GridlyLanguage.Arabic,
                "zh" => GridlyLanguage.Chinese,
                "ja" => GridlyLanguage.Japanese,
                _ => GridlyLanguage.English
            };
        }
    }

    public static string T(string key)
    {
        if (CustomTranslations.TryGetValue(key, out var custom)) return custom;
        if (!Texts.TryGetValue(key, out var perLang)) return key;
        var lang = EffectiveLanguage;
        if (perLang.TryGetValue(lang, out var value)) return value;
        return perLang.TryGetValue(GridlyLanguage.English, out var en) ? en : key;
    }

    public static string Filtering => T("Filtering");
    public static string FilterWindow(string column) => $"'{column}' {T("FilterWindowSuffix")}";
    public static string FilterStyle => T("FilterStyle");
    public static string SortAscending => T("SortAscending");
    public static string SortDescending => T("SortDescending");
    public static string Unsort => T("Unsort");
    public static string ClearSort => T("ClearSort");
    public static string UnsortColumn => T("UnsortColumn");
    public static string FreezeColumn => T("FreezeColumn");
    public static string ClearFrozenColumns => T("ClearFrozenColumns");
    public static string AutoSizeColumn => T("AutoSizeColumn");
    public static string AutoSizeAllColumns => T("AutoSizeAllColumns");
    public static string GroupByColumn(string column) => $"{T("GroupByColumnPrefix")} {column}";
    public static string CollapseAllGroups => T("CollapseAllGroups");
    public static string ExpandAllGroups => T("ExpandAllGroups");
    public static string ClearGrouping => T("ClearGrouping");
    public static string CollapseThisGroup => T("CollapseThisGroup");
    public static string ExpandThisGroup => T("ExpandThisGroup");
    public static string ShowOnlyThisGroup => T("ShowOnlyThisGroup");
    public static string ViewMode => T("ViewMode");
    public static string ChooseColumns => T("ChooseColumns");
    public static string ClearFilters => T("ClearFilters");
    public static string ClearAllFilters => T("ClearAllFilters");
    public static string ColumnFilterTitle(string column) => $"{column} {T("ColumnFilterSuffix")}";
    public static string SearchPlaceholder => T("SearchPlaceholder");
    public static string ApplyTypedTextAsFilter => T("ApplyTypedTextAsFilter");
    public static string SearchTypedTextInColumn => T("SearchTypedTextInColumn");
    public static string SelectAll => T("SelectAll");
    public static string Apply => T("Apply");
    public static string Clear => T("Clear");
    public static string SeparateFilterWindow => T("SeparateFilterWindow");
    public static string EmptyList => T("EmptyList");
    public static string EmptyValue => T("EmptyValue");
    public static string Copy => T("Copy");
    public static string Paste => T("Paste");
    public static string EditCell => T("EditCell");
    public static string RowDetails => T("RowDetails");
    public static string PopupMenu => T("PopupMenu");
    public static string ModalWindow => T("ModalWindow");
    public static string Both => T("Both");
    public static string ExtraLarge => T("ExtraLarge");
    public static string Large => T("Large");
    public static string Medium => T("Medium");
    public static string List => T("List");
    public static string Details => T("Details");
    public static string Tiles => T("Tiles");
    public static string Posters => T("Posters");
    public static string Columns => T("Columns");
    public static string ShowAll => T("ShowAll");
    public static string HideAll => T("HideAll");
    public static string DefaultColumnLayout => T("DefaultColumnLayout");
    public static string FitVisibleColumns => T("FitVisibleColumns");
    public static string ColumnChooserWindow => T("ColumnChooserWindow");
    public static string ColumnSearchPlaceholder => T("ColumnSearchPlaceholder");
    public static string Cancel => T("Cancel");
    public static string ClearColumnFilter => T("ClearColumnFilter");
    public static string CopyCell => T("CopyCell");
    public static string CopySelectionJson => T("CopySelectionJson");
    public static string CopyMiniAnalytics => T("CopyMiniAnalytics");
    public static string Mode => T("Mode");
    public static string Theme => T("Theme");
    public static string Sorting => T("Sorting");
    public static string FrozenColumn => T("FrozenColumn");
    public static string ColumnWidth => T("ColumnWidth");
    public static string Layout => T("Layout");
    public static string SaveDefaultLayoutProfile => T("SaveDefaultLayoutProfile");
    public static string LayoutProfiles => T("LayoutProfiles");
    public static string SaveUserLayout => T("SaveUserLayout");
    public static string LoadUserLayout => T("LoadUserLayout");
    public static string ResetUserLayout => T("ResetUserLayout");
    public static string ExportUserLayout => T("ExportUserLayout");
    public static string ImportUserLayout => T("ImportUserLayout");
    public static string Grouping => T("Grouping");
    public static string Freeze => T("Freeze");
    public static string View => T("View");
    public static string Clipboard => T("Clipboard");
    public static string Editing => T("Editing");
    public static string Analytics => T("Analytics");
    public static string BuiltInHeaderMenu => T("BuiltInHeaderMenu");
    public static string BuiltInMenuMergeText => T("BuiltInMenuMergeText");
    public static string FastPreviewLimitedInfo => T("FastPreviewLimitedInfo");
    public static string SearchingPreviewResults => T("SearchingPreviewResults");
    public static string PrintPreviewSuffix => T("PrintPreviewSuffix");

    public static string SaveColumnLayout => T("SaveColumnLayout");
    public static string LoadColumnLayout => T("LoadColumnLayout");
    public static string ResetColumnLayout => T("ResetColumnLayout");
    public static string ColumnChooserTitle => T("ColumnChooserTitle");
    public static string OK => T("OK");
    public static string FastPreviewInfo => T("FastPreviewInfo");
}

